### Imports

In [1]:
import sys
import pybinlex
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Load the dataset

In [2]:
# load the data
df = pd.read_csv('traits_sample.csv')
df.shape

(4124617, 18)

In [3]:
df['family'].value_counts()

family
Agensla          2967461
Adnur             338441
AccPhish          313893
Adond             257582
AdClicer          146737
AdLoad             44820
Agent              30365
AdBape             10604
Addrop             10457
AccountHunter       4066
Achis                191
Name: count, dtype: int64

### Resample data

In [4]:
# drop the family column that is below n threshold
n = 5000
traits_db = df[df['family'].map(df['family'].value_counts()) > n]

In [5]:
# resample the data to n samples per family
n = 12000
for family in traits_db['family'].unique():
    family_df = traits_db[traits_db['family'] == family]
    if family_df.shape[0] > n:
        traits_db = traits_db.drop(family_df.sample(family_df.shape[0] - n, random_state=42).index)

In [6]:
traits_db['family'].value_counts()

family
AccPhish    12000
AdClicer    12000
AdLoad      12000
Adnur       12000
Adond       12000
Agensla     12000
Agent       12000
AdBape      10604
Addrop      10457
Name: count, dtype: int64

In [7]:
# # remove traits that are 2 tokens or less
# traits_db = traits_db[traits_db['trait'].map(lambda x: len(x.split()) > 2)]

### Extract top n common traits from each family

In [8]:
n = 200
top_n_traits = pd.DataFrame()

# for each family, get the top n traits that are most frequent in that family
for family in traits_db['family'].unique():

    # get the top n traits for the family
    family_traits = traits_db[traits_db['family'] == family]['trait']
    result = family_traits.value_counts().head(n)
    
    # convert to dataframe
    result = pd.DataFrame(result)
    result.columns = ['count']
    result['family'] = family
    result['trait'] = result.index

    # reorder columns
    result = result[['family', 'trait', 'count']]
    result = result.reset_index(drop=True)

    # concat to top_n_traits
    top_n_traits = pd.concat([top_n_traits, result])

top_n_traits = top_n_traits.reset_index(drop=True)
top_n_traits

        family                                            trait  count
0     AccPhish                          8b c0 ff 25 ?? ?? ?? ??    160
1     AccPhish                                               c3    114
2     AccPhish                                         5e 5b c3     61
3     AccPhish                                ff 25 ?? ?? ?? ??     58
4     AccPhish                                      5f 5e 5b c3     50
...        ...                                              ...    ...
1795     Agent              57 ff 15 ?? ?? ?? ?? e9 7f 08 00 00      9
1796     Agent                 e8 5d e2 ff ff 80 7d ?? ?? 74 0a      9
1797     Agent                       3b 45 ?? 0f 85 ad 0f 00 00      9
1798     Agent  8b 01 51 ff 50 ?? be 01 40 00 80 e9 6f 01 00 00      9
1799     Agent              0f b7 4f ?? 83 e9 30 89 4d ?? eb d9      9

[1800 rows x 3 columns]

In [9]:
# # remove traits that appear in more than n families
# n = 5
# top_n_traits = top_n_traits[top_n_traits['trait'].map(top_n_traits['trait'].value_counts()) <= n]
# top_n_traits

In [10]:
# save the top n traits to csv
top_n_traits.to_csv('top_n_traits.csv', index=False)

### Extract sample traits from a malware

In [13]:
path = "Copy of Trojan-PSW.MSIL.Agensla.uyn-03c6ec94511f79ea5315870ca752e55f074581382a9e33ea403281e3bec95968"

# load the target PE file
pe = pybinlex.PE()
result = pe.read_file(path)

# check if the PE file was read successfully
if result is False: sys.exit(1)

# disassemble the PE file
disassembler = pybinlex.Disassembler(pe)
disassembler.disassemble()

# get the disassembled code traits
sample_traits = disassembler.get_traits()

# convert to df
sample_traits = pd.DataFrame(sample_traits, columns=['trait', 'family'])

# get top n traits
sample_traits = sample_traits['trait'].value_counts().head(100)
sample_traits = pd.DataFrame(sample_traits)
sample_traits.columns = ['count']
sample_traits['trait'] = sample_traits.index
sample_traits = sample_traits.reset_index(drop=True)
sample_traits = sample_traits[['trait', 'count']]
sample_traits

                                                trait  count
0                 0f b6 7e ?? 0f b6 42 ?? 2b f8 74 16    187
1     33 c0 85 c9 0f 9f c0 8d 0c 45 ?? ?? ?? ?? eb 02    102
2                 0f b6 4e ?? 0f b6 42 ?? 2b c8 74 12     97
3                                               eb 04     72
4                 8b 46 ?? 3b 42 ?? 0f 84 81 00 00 00     63
..                                                ...    ...
95                8b 46 ?? 3b 42 ?? 0f 84 82 00 00 00     15
96                                     83 f8 02 74 08     15
97  8b cf e8 28 9e 00 00 bd ff ff ff 3f be 00 ca 9...     15
98  50 e8 31 66 01 00 8b f8 59 85 ff 0f 84 b7 00 0...     15
99  88 83 ?? ?? ?? ?? c6 83 ?? ?? ?? ?? ?? c7 83 ?...     15

[100 rows x 2 columns]

### Find Common traits

In [14]:
results = {}
for family in top_n_traits['family'].unique():
    c = 0
    for x in sample_traits['trait']:
        if x in top_n_traits[top_n_traits['family'] == family]['trait'].tolist():
            c += 1

    results[family] = c

results = pd.DataFrame(results.items(), columns=['family', 'count'])
results = results.sort_values(by='count', ascending=False)
results = results.reset_index(drop=True)
results

     family  count
0   Agensla     18
1     Adnur      9
2  AccPhish      8
3    AdLoad      6
4     Adond      6
5     Agent      5
6  AdClicer      4
7    AdBape      0
8    Addrop      0